using CheekyModels.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CheekyData.Configurations
{
    public class SkillConfiguration : IEntityTypeConfiguration<Skill>
    {
        public void Configure(EntityTypeBuilder<Skill> builder)
        {
            builder.ToTable("Skill");
            builder.HasKey(s => s.SkillId);

            builder.Property(p => p.SkillId).ValueGeneratedOnAdd();
            builder.Property(p => p.SkillName).IsRequired();

            builder.HasOne(a => a.SkillType)
                   .WithMany(a => a.Skills)
                   .HasForeignKey(a => a.SkillTypeId);

            builder.ToTable("Skill").HasData(InitialSkillSeed());
        }

        private static IEnumerable<Skill> InitialSkillSeed()
        {
            return new List<Skill>
            {
                // Core Skills
                new() { SkillId = Guid.NewGuid(), SkillName = "C", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "CSS", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "HTML", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "JAVA", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "JAVASCRIPT", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "KOTLIN", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "OBJECTIVE-C", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "PHP", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "PYTHON", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "RUBY", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "SQL", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "SWIFT", SkillTypeId = 1 },
                new() { SkillId = Guid.NewGuid(), SkillName = "XML", SkillTypeId = 1 },
                
                // Technical Skills
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-1.0", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-1_1", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-2.0", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-3.5", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-4.0", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-4.5", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-4.5.1", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-4.6", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-4.7", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-4.8", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-5", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-6", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-CORE-7", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = ".NET-FRAMEWORK", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "ACCEPTANCE-TESTS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AGILE-FRAMEWORK", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-CLOUDFRONT", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-COGNITO", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-DYNAMODB", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-EC2", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-ELASTICACHE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-ELASTICSEARCH-ES", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-EMR", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-INSPECTOR", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-QUICKSIGHT", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-RDS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-ROUTE-53", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-S3", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-SAGEMAKER", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-SNS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-SQS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AMAZON-VPC", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "ANDROID", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "ANGULAR", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "ANSIBLE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "APACHE-HADOOP-MAHOUT", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "ARM-TEMPLATES", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AURELIA", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AUTH0", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AUTOMATION-ANYWHERE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AUTOMATION-TESTS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-CONFIG", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-CONTROL-TOWER", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-DEVELOPER-TOOLS-CODEBUILD-CODECOMMIT-CODEDEPLOY-CODESTAR", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-DIRECT-CONNECT", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-ELASTIC-BEANSTALK", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-FARGATE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-GLUE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-IDENTITY-ACCESS-MANAGEMENT", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-KEY-MANAGEMENT-SERVICE-KMS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-LAMBDA", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-ORGANIZATIONS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-SERVICE-CATALOG", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-SYSTEMS-MANAGER", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-TRANSIT-GATEWAY", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AWS-WAF", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-ACTIVE-DIRECTORY", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-AD-B2C", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-API-MANAGEMENT-APIM", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-APP-INSIGHTS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-APP-SERVICES", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-BLOB-STORAGE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-COGNITIVE-SEARCH", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-CONTENT-DELIVERY-NETWORK", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-COSMOS-DB", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-DATA-FACTORY", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-DATA-LAKE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-DATABRICKS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-EVENT-GRID", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-EVENT-HUBS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-FRONT-DOOR", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-FUNCTIONS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-KEY-VAULT", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-KUBERNETES-SERVICE-AKS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-LOGIC-APPS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-MONITOR", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-NOTIFICATION-HUBS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-POWER-AUTOMATE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-SERVICE-BUS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-SIGNALR", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-SQL-DATABASE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-SYNAPSE-ANALYTICS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "AZURE-TABLE-STORAGE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "BICEP", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "BLUEPRISM", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "CI-CD", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "CODE-REVIEW-PROCESS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "DATAIQ", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "DEPENDENCY-INJECTION", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "DEVELOPMENT-STANDARDS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "DOCKER", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "ELASTIC-STACK", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "ETL", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "EVENT-DRIVEN-ARCHITECTURE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "GCP", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "GCP-AUTOML", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "GCP-BIGQUERY", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "GCP-DATAFLOW", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "GCP-DATAFORM", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "GCP-DATASTUDIO", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "GCP-KUBERNETES-ENGINE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "GDS-STANDARDS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "GITHUB-ACTIONS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "GITLAB-RUNNERS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "INFRASTRUCTURE-AS-CODE-IAC", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "INTEGRATION-TESTS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "IOS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "JENKINS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "JUPYTER", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "KAFKA", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "LOAD-TESTING", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "MICROSOFT-SQL-SERVER-ANALYSIS-SERVICES-SSAS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "MICROSOFT-SQL-SERVER-INTEGRATION-SERVICES-SSIS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "MONGODB", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "NODEJS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "OAUTH2-OIDC", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "OBJECT-ORIENTED-PROGRAMMING", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "OKTA", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "PERFORMANCE-TESTING", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "PYTORCH", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "QLIKSENSE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "REACT", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "REACT-NATIVE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "RELATIONAL-DATABASES", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "REMIX", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "SCALED-AGILE-FRAMEWORK-SAFE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "SCRUM", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "SOURCE-CONTROL-MANAGEMENT-GIT-SVN-MERCURIAL-TFS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "SPOTFIRE", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "STARBURST-GALAXY", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "TABLEAU", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "TEAMCITY", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "TENSORFLOW", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "TYPESCRIPT", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "UNIT-TESTS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "VUE-JS", SkillTypeId = 2 },
                new() { SkillId = Guid.NewGuid(), SkillName = "XAMARIN", SkillTypeId = 2 },
            };
        }
    }
}
