// <auto-generated />
using System;
using CheekyData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheekyData.Migrations
{
    [DbContext(typeof(CheekyContext))]
    partial class CheekyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheekyModels.Entities.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("RatingName")
                        .IsRequired()
                        .HasMaxLength(52)
                        .HasColumnType("nvarchar(52)");

                    b.HasKey("RatingId");

                    b.ToTable("Rating", (string)null);

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            RatingName = "1 - Awareness"
                        },
                        new
                        {
                            RatingId = 2,
                            RatingName = "2 - Novice"
                        },
                        new
                        {
                            RatingId = 3,
                            RatingName = "3 - Professional"
                        },
                        new
                        {
                            RatingId = 4,
                            RatingName = "4 - Expert"
                        },
                        new
                        {
                            RatingId = 5,
                            RatingName = "5 - Leading-edge expert"
                        },
                        new
                        {
                            RatingId = 6,
                            RatingName = "1 - Beginner"
                        },
                        new
                        {
                            RatingId = 7,
                            RatingName = "2 - Want to improve"
                        },
                        new
                        {
                            RatingId = 8,
                            RatingName = "3 - Proffesional"
                        },
                        new
                        {
                            RatingId = 9,
                            RatingName = "4 - Expert"
                        },
                        new
                        {
                            RatingId = 10,
                            RatingName = "5 - Leading-edge expert"
                        });
                });

            modelBuilder.Entity("CheekyModels.Entities.ScrapedNews", b =>
                {
                    b.Property<Guid>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NewsId");

                    b.ToTable("ScrapedNews", (string)null);

                    b.HasData(
                        new
                        {
                            NewsId = new Guid("fde34b5e-5b1a-46d6-9fe7-b6896cf86517"),
                            ImageUrl = "Pretend IMG URL",
                            PageUrl = "Pretend Page URL",
                            Title = "First Random Title for News"
                        });
                });

            modelBuilder.Entity("CheekyModels.Entities.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillTypeId")
                        .HasColumnType("int");

                    b.HasKey("SkillId");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("Skill", (string)null);

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("31d090ff-9498-44b3-a57c-89938932a024"),
                            SkillName = "C",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("36e60458-065e-4447-af25-8e2ad2d8d58a"),
                            SkillName = "CSS",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("8a237711-73c3-48e6-9379-eca2cab1946f"),
                            SkillName = "HTML",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("5e8e6fca-8a81-4606-a737-7f03345d3ddd"),
                            SkillName = "Java",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("a5891511-3294-4617-8f77-3be301983e0a"),
                            SkillName = "JavaScript",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("a7a85903-5def-42e5-a3ec-18d0a917064e"),
                            SkillName = "Kotlin",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("a26aa383-00f5-4bf7-bc1a-7ee7b2665a1c"),
                            SkillName = "Objective-C",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("c9a2296e-f9ef-479f-923e-72517510f7c6"),
                            SkillName = "PHP",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("8c4ddc44-56bf-4c9d-8d75-2160e6bdcdf3"),
                            SkillName = "Python",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("3d0667ca-8335-4386-8b22-e61d04496dfc"),
                            SkillName = "Ruby",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("c00d14b0-5673-4e16-b663-4d364619eb94"),
                            SkillName = "SQL",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("353dc2a1-fe50-418b-a093-110bbc017fc4"),
                            SkillName = "Swift",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("306dc35c-0814-49a7-91f4-b200a9b483de"),
                            SkillName = "TypeScript",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("f8334bee-9820-4670-a761-c128847a3ef0"),
                            SkillName = "XML",
                            SkillTypeId = 1
                        },
                        new
                        {
                            SkillId = new Guid("c973da66-cb33-4ce6-a3c0-1332db89e923"),
                            SkillName = "Net-Core-5",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("0c20b3c8-0dfd-4e48-974b-325aba71f33b"),
                            SkillName = "Net-Framework",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("9aea7d1c-96c1-4d29-bdb8-8f488c5d22cd"),
                            SkillName = "Acceptance-tests",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("4f1641c1-caa4-4efb-9d15-3c6c867f5297"),
                            SkillName = "Agile-Framework",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("57d80b18-7cd8-42a7-9d47-d6b0517f6919"),
                            SkillName = "Amazon-CloudFront",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("d7ba6b2b-6a89-47a2-8a3e-8c8e683a144a"),
                            SkillName = "Amazon-Cognito",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("ed864c31-4a62-4dd0-baec-6d9982dd74d0"),
                            SkillName = "Amazon-DynamoDB",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("c861bf87-7b12-4cc0-99b1-0989df3a7ce1"),
                            SkillName = "Amazon-EC2",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("6f625dc4-0df8-458e-ab48-9e5f450f33d4"),
                            SkillName = "Amazon-ElastiCache",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("daa422a5-1cd0-4a43-88aa-0878097089b5"),
                            SkillName = "Amazon-Elasticsearch-ES",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("b28f1f07-44e4-46a2-b188-80882ca75749"),
                            SkillName = "Amazon-EMR",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("2e79354d-7c63-4101-af84-0c90e60add1e"),
                            SkillName = "Amazon-Inspector",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("419d2fa2-bf7d-4199-92ff-6db951234c93"),
                            SkillName = "Amazon-QuickSight",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("585b6fea-6375-44f7-b87b-4fc1cfaaa044"),
                            SkillName = "Amazon-RDS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("28bfa887-bbbb-4511-bea0-9927e502b5ac"),
                            SkillName = "Amazon-Route-53",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("c60aa924-ee18-43b5-b34a-33331b1f30bd"),
                            SkillName = "Amazon-S3",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("84db8b00-1f1c-4729-a28f-9719ec6989b9"),
                            SkillName = "Amazon-SageMaker",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("7bfa93b5-dc06-43bd-8bfe-42ebac64997f"),
                            SkillName = "Amazon-SNS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("b0076bb0-9b18-49ae-a8f3-a3cde41d24ed"),
                            SkillName = "Amazon-SQS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("61a82168-703b-4a4a-ad70-5435cd3bf277"),
                            SkillName = "Amazon-VPC",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("65e34f22-e16d-4594-b24a-3fa359198c5d"),
                            SkillName = "Android",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("738084fd-4223-41c0-ad6d-96331158b546"),
                            SkillName = "Angular",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("ec7ead8e-e715-4616-bfa5-eb06a25c769c"),
                            SkillName = "Ansible",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("b3c467ef-0adc-4f54-b8ac-029bc4f9fc7a"),
                            SkillName = "Apache-Hadoop-Mahout",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("afe8e63b-a558-4a97-a31a-5b96db3adfc3"),
                            SkillName = "ARM-Templates",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("46e68ba9-ac55-43ac-bf6e-21a93d757aba"),
                            SkillName = "Aurelia",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("cacb9d89-a943-4670-8155-ab2711471ada"),
                            SkillName = "Auth0",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("b951fa79-1287-4a95-801d-6c38342f4bea"),
                            SkillName = "Automation-Anywhere",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("78553148-8574-48f1-83e2-ed3214edae58"),
                            SkillName = "Automation-tests",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("e179bf3e-41e2-4388-ba50-8a6312c7fc50"),
                            SkillName = "AWS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("c4dfe58d-c2c6-42f7-bc0b-3c337fcc4e71"),
                            SkillName = "AWS-Config",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("1dd73145-24e5-4ae9-9ba9-8574bf2c2eb3"),
                            SkillName = "AWS-Control-Tower",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("6f57a01b-4e0a-46ef-a4e5-44736cd081b8"),
                            SkillName = "AWS-Developer-Tools-CodeBuild-CodeCommit-CodeDeploy-CodeStar",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("06f3f716-1911-443b-876b-c08b9a44ccfa"),
                            SkillName = "AWS-Direct-Connect",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("7ac73456-3365-487b-8d24-ae1dff5d7652"),
                            SkillName = "AWS-Elastic-Beanstalk",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("6426dea5-6288-4e66-979a-8090b2085f00"),
                            SkillName = "AWS-Fargate",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("438d4f5b-c93f-465a-9ed6-32e9ae0c3579"),
                            SkillName = "AWS-Glue",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("ff46479f-b9ca-45c7-a846-1510f13c8ca1"),
                            SkillName = "AWS-Identity-Access-Management",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("ce953a30-2af3-4392-a88a-9f67e9772ad8"),
                            SkillName = "AWS-Key-Management-Service-KMS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("bdca5887-c81b-4201-aa8a-97420f8ea823"),
                            SkillName = "AWS-Lambda",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("55630cb5-32f7-4969-becc-de52a1b54b60"),
                            SkillName = "AWS-Organizations",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("40075973-77f2-4e88-a115-0291bfe620b2"),
                            SkillName = "AWS-Service-Catalog",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("74b8c779-d580-4160-989b-c5f75f9471ee"),
                            SkillName = "AWS-Systems-Manager",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("280522c9-dda4-4977-9cfe-e7c740862534"),
                            SkillName = "AWS-Transit-Gateway",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("a51b314d-b3d3-4547-81f6-42725874ec1f"),
                            SkillName = "AWS-WAF",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("8ef065ad-74f0-49b1-8db6-b9e86ffa76e4"),
                            SkillName = "Azure",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("b98f5e05-03ba-4852-a789-530209ade76d"),
                            SkillName = "Azure-Active-Directory",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("7e0d8046-531a-431f-a5aa-c42c6e9a7e90"),
                            SkillName = "Azure-AD-B2C",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("10bdc99c-7abb-4f2c-9183-893e36b9524c"),
                            SkillName = "Azure-API-Management-APIM",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("d611a6dd-abf1-4684-b0d6-182be55847bb"),
                            SkillName = "Azure-App-Insights",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("4815c219-c183-438d-8100-7045cce88221"),
                            SkillName = "Azure-App-Services",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("60b5aec6-e6ad-4e3a-8e5d-55fffed639f0"),
                            SkillName = "Azure-Blob-Storage",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("d0ced1d9-b33c-4a56-b420-2c0f52e22320"),
                            SkillName = "Azure-Cognitive-Search",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("2767fc96-b870-43d1-9d71-51b6fa41066c"),
                            SkillName = "Azure-Content-Delivery-Network",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("8d33bc34-b06a-4668-8c88-420b58bbba07"),
                            SkillName = "Azure-Cosmos-DB",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("0428d200-3a84-43ab-9e65-97257fb91cb9"),
                            SkillName = "Azure-Data-Factory",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("decc81da-8988-48ca-979f-520c0dc7de38"),
                            SkillName = "Azure-Data-Lake",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("827bcb71-9a16-42b5-a920-e4a998d209e3"),
                            SkillName = "Azure-Databricks",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("231de9af-f3cc-4f30-8bae-e3e9fb3e29c0"),
                            SkillName = "Azure-Event-Grid",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("e6de1791-5791-422f-a8d6-a62256be429b"),
                            SkillName = "Azure-Event-Hubs",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("8ef1c7f6-9253-4ba1-8dcf-f720b1bcab13"),
                            SkillName = "Azure-Front-Door",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("e18c8b80-5387-4032-8521-15aa0091653a"),
                            SkillName = "Azure-Functions",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("40b8b895-7d28-4836-8acd-c7ab4cfd8d5d"),
                            SkillName = "Azure-Key-Vault",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("b4bf7ff2-7f59-49b2-bfc5-319589617c31"),
                            SkillName = "Azure-Kubernetes-Service-AKS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("bfdfc00b-eb9c-4a81-8da0-9c7dadbb7854"),
                            SkillName = "Azure-Logic-Apps",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("af25415e-c60e-42de-885d-5a39193c6541"),
                            SkillName = "Azure-Monitor",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("4016eb31-5167-46a0-9ece-7365e1fb0d0a"),
                            SkillName = "Azure-Notification-Hubs",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("154ced79-5451-4a18-9ab4-b1352666d282"),
                            SkillName = "Azure-Power-Automate",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("94cd9da0-d0d0-488c-983c-966f5eb075f3"),
                            SkillName = "Azure-Service-Bus",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("04e407df-bfa0-41e8-a70f-d511889b0eb1"),
                            SkillName = "Azure-SignalR",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("1558b128-5c1a-4886-9da9-3a471d9454be"),
                            SkillName = "Azure-SQL-Database",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("b133dd55-295b-4c8a-a079-29d0b85787c3"),
                            SkillName = "Azure-Synapse-Analytics",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("f0499d22-d799-4bb3-b9c1-b8631ae2ce34"),
                            SkillName = "Azure-Table-Storage",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("65942a20-da3a-4b5a-9c43-6c0f7d50f70f"),
                            SkillName = "Bicep",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("13fc0d39-456d-4986-bf1a-3bb8bae43c2a"),
                            SkillName = "BluePrism",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("0943362b-aeaf-4263-be62-683f50aa1f39"),
                            SkillName = "CI-CD",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("c479eea4-9e89-4e3f-9cea-b3c3c07ab45e"),
                            SkillName = "Code-review-process",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("2e93ed01-8a22-4f96-9f35-35f5df79bf97"),
                            SkillName = "DataIQ",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("a0428ac4-4e59-4dd7-b10f-02cbb08c1f81"),
                            SkillName = "Dependency-injection",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("cfb72d25-2a6e-40ac-91d3-60bc2b9363cf"),
                            SkillName = "Development-standards",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("b8471b64-aaad-4c3e-a2e6-bd9d42669d43"),
                            SkillName = "Docker",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("29d97e79-2c0b-44a1-aa25-403a38136408"),
                            SkillName = "Elastic-Stack",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("7eecade8-2ffa-469f-8991-2c4b1494cef3"),
                            SkillName = "ETL",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("61b59924-c557-419c-b843-d3773c7f93df"),
                            SkillName = "Event-driven-architecture",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("47668a52-b199-4ade-ba3e-5076cb95e795"),
                            SkillName = "GCP",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("314cd338-5b92-49d6-9543-36001f7b95b2"),
                            SkillName = "GCP-AutoML",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("4e175ad6-0060-4a5f-ae17-e5134668f1d6"),
                            SkillName = "GCP-BigQuery",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("40811d7e-e40b-4cb9-b931-1d2c5c662635"),
                            SkillName = "GCP-DataFlow",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("85a434ae-c224-4c2d-b336-acf5d49aa643"),
                            SkillName = "GCP-Dataform",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("916daf71-9c16-4edf-bf47-c06f4bf7939f"),
                            SkillName = "GCP-DataStudio",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("e2ec434b-03f8-42cd-b5cd-ea6f9f7b76f2"),
                            SkillName = "GCP-Kubernetes-Engine",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("063cd782-d26f-4060-8528-1371a52b7284"),
                            SkillName = "GDS-standards",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("f8c66873-1021-454d-8120-c2c616b748d1"),
                            SkillName = "GitHub-Actions",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("bc8042d3-413d-4849-bd3b-a92f0ec9b82e"),
                            SkillName = "GitLab-Runners",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("420e68b9-e0a2-413d-8467-b7bac0e90dca"),
                            SkillName = "Infrastructure-as-Code-IaC",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("d7ed19b9-2982-4219-840f-f3f8e8e5f0b4"),
                            SkillName = "Integration-tests",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("5026fc9b-144e-4db7-a6b8-4e9928351978"),
                            SkillName = "iOS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("ab952daf-b2b3-4526-8e54-c0af94a52260"),
                            SkillName = "Jenkins",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("d04f7798-99f4-412b-9bdf-175a16f1995e"),
                            SkillName = "Jupyter",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("fed956d2-51f3-4342-b638-093d61e9015b"),
                            SkillName = "Kafka",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("d1b61751-68f0-4df0-8e7e-e5c50495508e"),
                            SkillName = "Load-testing",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("b044816e-c434-49ea-a567-a9ea0773fad8"),
                            SkillName = "Microsoft-SQL-Server-Analysis-Services-SSAS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("347a4d51-f8b3-4991-8d79-a4a1ac643074"),
                            SkillName = "Microsoft-SQL-Server-Integration-Services-SSIS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("28de7cb2-6155-4b25-8543-2b4181a4f24a"),
                            SkillName = "MongoDB",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("2a433e9f-b120-4766-ba5e-9cf21f0405da"),
                            SkillName = "NodeJS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("13bc224c-a0c3-4d9d-b988-970fc9ebf043"),
                            SkillName = "OAuth2-OIDC",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("94780c8b-7494-4a0a-9080-0d89a5986728"),
                            SkillName = "Object-oriented-programming",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("5c693e06-81b1-4540-bde4-40def3212765"),
                            SkillName = "Okta",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("3b6fa9f3-2832-4e82-a07c-42775eacb758"),
                            SkillName = "Performance-testing",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("26ddc6fd-90f3-45b5-9b60-2c1816704985"),
                            SkillName = "PHP",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("cd7a9993-2dfe-4720-9e9f-46cc0e8aa82b"),
                            SkillName = "Python",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("59f7a3be-6d36-4b36-9fea-82de6cb93ba5"),
                            SkillName = "PyTorch",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("727eeb8e-cbae-4fc2-84f4-409292ea5b67"),
                            SkillName = "QlikSense",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("d3613d83-6306-41f1-8318-a78664c129bb"),
                            SkillName = "React",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("326f4b78-4f09-49c9-8413-b0010b75397d"),
                            SkillName = "React-Native",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("3bca547a-42f3-4adf-8f25-aea3a4af6bfd"),
                            SkillName = "Relational-databases",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("eaf5cd4b-db04-4363-936f-687672efeaa7"),
                            SkillName = "Remix",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("67b54312-5d95-4ff6-a34c-fed98288f369"),
                            SkillName = "Ruby",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("5e1128bb-b33b-440d-ab82-e8a107a0455b"),
                            SkillName = "Scaled-Agile-Framework-SAFe",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("ef9d9a8f-f492-4f38-90bc-d1ea4fc0ebea"),
                            SkillName = "Scrum",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("b1734732-35bb-4921-b11f-da11e645ed3d"),
                            SkillName = "Source-Control-Management-Git-SVN-Mercurial-TFS",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("886b43dd-df46-42f8-a29b-1fb409abab08"),
                            SkillName = "Spotfire",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("c72feb91-db02-4c55-a1f9-5896191b5528"),
                            SkillName = "SQL",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("668aa525-551c-4b3f-81bc-a44176abd54b"),
                            SkillName = "Starburst-Galaxy",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("f753743f-00f3-4fcb-a8b7-8b2c9cef7472"),
                            SkillName = "Swift",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("ff35e9d9-7562-41d3-adca-cd64c5c77090"),
                            SkillName = "Tableau",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("a3c04778-28f1-428d-a966-ba32284fd9ff"),
                            SkillName = "TeamCity",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("9c1a462e-c024-485f-93ee-6fc963fa14cc"),
                            SkillName = "Tensorflow",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("d36d68ac-8e16-46ad-a7e5-b3f271127b1e"),
                            SkillName = "Typescript",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("836c9f64-11b6-4772-92d7-faacf8225ce1"),
                            SkillName = "Unit-tests",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("8977ebee-e966-4ba2-958b-3c1c2415d38d"),
                            SkillName = "Vue-js",
                            SkillTypeId = 2
                        },
                        new
                        {
                            SkillId = new Guid("bc48e034-2c7b-4bba-a47c-5522184af5d5"),
                            SkillName = "Xamarin",
                            SkillTypeId = 2
                        });
                });

            modelBuilder.Entity("CheekyModels.Entities.SkillType", b =>
                {
                    b.Property<int>("SkillTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("SkillTypeId");

                    b.ToTable("SkillType", (string)null);

                    b.HasData(
                        new
                        {
                            SkillTypeId = 1,
                            Name = "Core"
                        },
                        new
                        {
                            SkillTypeId = 2,
                            Name = "Technical"
                        });
                });

            modelBuilder.Entity("CheekyModels.Entities.SkillTypeRating", b =>
                {
                    b.Property<int>("SkillTypeId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("SkillTypeId", "RatingId");

                    b.HasIndex("RatingId");

                    b.ToTable("SkillTypeRating");
                });

            modelBuilder.Entity("CheekyModels.Entities.ToDo", b =>
                {
                    b.Property<Guid>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ToDoDateModified")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("datetime2");

                    b.Property<string>("ToDoMessage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ToDoTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ToDoId");

                    b.HasIndex("UserId");

                    b.ToTable("ToDo", (string)null);

                    b.HasData(
                        new
                        {
                            ToDoId = new Guid("fde34b5e-5b1a-46d6-9fe7-b6896cf86517"),
                            ToDoDateModified = new DateTime(2023, 6, 10, 18, 8, 45, 555, DateTimeKind.Utc).AddTicks(7409),
                            ToDoMessage = "Well there was one day the ended and the new day started",
                            ToDoTitle = "Something about something 1",
                            UserId = new Guid("830e9471-9d6e-4557-8bf5-ec89d375d933")
                        },
                        new
                        {
                            ToDoId = new Guid("59887cb4-62be-4d64-a7cf-70a608c84d7b"),
                            ToDoDateModified = new DateTime(2023, 6, 10, 18, 8, 45, 555, DateTimeKind.Utc).AddTicks(7416),
                            ToDoMessage = "Well there was one day the ended and the new day started",
                            ToDoTitle = "Something about something 2",
                            UserId = new Guid("830e9471-9d6e-4557-8bf5-ec89d375d933")
                        },
                        new
                        {
                            ToDoId = new Guid("f783e4e6-f492-4ecf-8362-fd4834ab37d7"),
                            ToDoDateModified = new DateTime(2023, 6, 10, 18, 8, 45, 555, DateTimeKind.Utc).AddTicks(7419),
                            ToDoMessage = "Well there was one day the ended and the new day started",
                            ToDoTitle = "Something about something 3",
                            UserId = new Guid("830e9471-9d6e-4557-8bf5-ec89d375d933")
                        },
                        new
                        {
                            ToDoId = new Guid("5fce3a3a-a421-4830-a49b-f8813d6d4fb9"),
                            ToDoDateModified = new DateTime(2023, 6, 10, 18, 8, 45, 555, DateTimeKind.Utc).AddTicks(7428),
                            ToDoMessage = "Well there was one day the ended and the new day started",
                            ToDoTitle = "Something about something",
                            UserId = new Guid("830e9471-9d6e-4557-8bf5-ec89d375d933")
                        });
                });

            modelBuilder.Entity("CheekyModels.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Archived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ArchivedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GoogleUserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("830e9471-9d6e-4557-8bf5-ec89d375d933"),
                            Archived = false,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "AmirShaw@hotmail.co.uk",
                            FirstName = "Amir",
                            ModifiedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Surname = "Shaw"
                        });
                });

            modelBuilder.Entity("CheekyModels.Entities.UserSkill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastEvaluated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasKey("SkillId", "UserId");

                    b.HasIndex("RatingId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("CheekyModels.Entities.Skill", b =>
                {
                    b.HasOne("CheekyModels.Entities.SkillType", "SkillType")
                        .WithMany("Skills")
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillType");
                });

            modelBuilder.Entity("CheekyModels.Entities.SkillTypeRating", b =>
                {
                    b.HasOne("CheekyModels.Entities.Rating", "Ratings")
                        .WithMany("SkillTypeRating")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheekyModels.Entities.SkillType", "SkillType")
                        .WithMany("SkillTypeRating")
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ratings");

                    b.Navigation("SkillType");
                });

            modelBuilder.Entity("CheekyModels.Entities.ToDo", b =>
                {
                    b.HasOne("CheekyModels.Entities.User", "User")
                        .WithMany("ToDos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CheekyModels.Entities.UserSkill", b =>
                {
                    b.HasOne("CheekyModels.Entities.Rating", "Rating")
                        .WithMany("UserSkills")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheekyModels.Entities.Skill", "Skill")
                        .WithMany("Users")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheekyModels.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CheekyModels.Entities.Rating", b =>
                {
                    b.Navigation("SkillTypeRating");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("CheekyModels.Entities.Skill", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CheekyModels.Entities.SkillType", b =>
                {
                    b.Navigation("SkillTypeRating");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("CheekyModels.Entities.User", b =>
                {
                    b.Navigation("ToDos");

                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
